VERSION=$(shell git describe --tags)
OUTPUTICONGOFILE="lemon/icon.go"

build:
	go build -ldflags "-s -w -X github.com/Rehtt/lemonade/lemon.Version=$(VERSION)"

install:
	go install -ldflags "-s -w -X github.com/Rehtt/lemonade/lemon.Version=$(VERSION)"

release:
	gox --arch 'amd64 386' --os 'windows linux darwin' --output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}/{{.Dir}}" -ldflags "-s -w -X github.com/Rehtt/lemonade/lemon.Version=$(VERSION)"
	zip      pkg/lemonade_windows_386.zip     dist/lemonade_windows_386/lemonade.exe   -j
	zip      pkg/lemonade_windows_amd64.zip   dist/lemonade_windows_amd64/lemonade.exe -j
	tar zcvf pkg/lemonade_linux_386.tar.gz    -C dist/lemonade_linux_386/    lemonade
	tar zcvf pkg/lemonade_linux_amd64.tar.gz  -C dist/lemonade_linux_amd64/  lemonade
	tar zcvf pkg/lemonade_darwin_386.tar.gz   -C dist/lemonade_darwin_386/   lemonade
	tar zcvf pkg/lemonade_darwin_amd64.tar.gz -C dist/lemonade_darwin_amd64/ lemonade

clean:
	rm -rf dist/
	rm -f pkg/*.tar.gz pkg/*.zip

icon:
	xxd -i lemon/icon.ico > lemon/icon.hex
	echo "// generated by Makefile" > "$(OUTPUTICONGOFILE)"
	echo "// DO NOT EDIT" >> "$(OUTPUTICONGOFILE)"
	echo "" >> "$(OUTPUTICONGOFILE)"
	echo "package lemon" >> "$(OUTPUTICONGOFILE)"
	echo "" >> "$(OUTPUTICONGOFILE)"
	echo "var Icon = []byte{" >> "$(OUTPUTICONGOFILE)"
	sed 's/unsigned char.*{//' lemon/icon.hex | sed 's/unsigned int.*;//' |  sed 's/};//' | sed '/^$$/d' | sed '$$ s/$$/,/' >> "$(OUTPUTICONGOFILE)"
	echo "}" >> "$(OUTPUTICONGOFILE)"
	go fmt "$(OUTPUTICONGOFILE)"
	rm lemon/icon.hex

build_windows_gui:
	GOOS=windows go build -ldflags "-s -w -X github.com/Rehtt/lemonade/lemon.Version=$(VERSION) -X github.com/Rehtt/lemonade/lemon.Gui=gui"
